version: '3'
networks:
  homeland:
    driver: bridge
services:
  config-server:
    image: johnjonathan/spring-cloud-config-server:1.0.0
    container_name: config-server
    ports:
      - 8888:8888
    volumes:
      - ./config:/config
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - BANNER_LOCATION=file:/config/banner.txt
    networks:
      - homeland
  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: me_user
      ME_CONFIG_BASICAUTH_PASSWORD: me_pwd
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_pwd
    links:
      - mongo
    networks:
      - homeland
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
      MONGO_INITDB_DATABASE: waes_api
    ports:
      - 27017:27017
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d/
    networks:
      - homeland
  waes-api:
    image: johnjonathan/waes-scalable-web:1.0.0
    container_name: waes-api
    ports:
      - 8080:8080
    depends_on: 
      - config-server
    command: dockerize -wait tcp://config-server:8888 tcp://mongo:27017
    networks:
      - homeland
